// preact-todomvc/src/app.jsx
import { signal, computed, effect } from '@preact/signals'

const STORAGE_KEY = 'todos-preact'

const filters = {
  all: (todos) => todos,
  active: (todos) => todos.filter((todo) => !todo.completed),
  completed: (todos) => todos.filter((todo) => todo.completed)
}

const visibility = signal('all')

function onHashChange() {
  const route = window.location.hash.replace(/#\/?/, '')
  if (filters[route]) {
    visibility.value = route
  } else {
    window.location.hash = ''
    visibility.value = 'all'
  }
}

window.addEventListener('hashchange', onHashChange)
onHashChange()

const editedTodo = signal(null);
const todos = signal(JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'))
const filteredTodos = computed(() => filters[visibility.value](todos.value))
const remaining = computed(() => filters.active(todos.value).length)

export function App() {
  const addTodo = (event) => {
    if (event.key === 'Enter') {
      const value = event.target.value.trim()
      if (value) {
        todos.value = [...todos.value,
          {
            id: Date.now(),
            title: value,
            completed: false,
          }
        ]
        event.target.value = ''
      }
    }
  }

  const removeTodo = (index) => {
    const array = [...todos.value]
    array.splice(index, 1)
    todos.value = array
  }

  const toggleAll = (e) => {
    todos.value = todos.value.map(v => ({...v, completed: e.target.checked}))
  }

  const editTodo = (index) => {
    editedTodo.value = index
    setTimeout(() => {
      document.querySelector('.todo-edit').focus()
    }, 10);
  }
  
  const doneEdit = (value, index) => {
    if (editedTodo.value !== null) {
      editedTodo.value = null
      if(value) {
        todos.value = todos.value.map((t,i) => i === index ? {...t, title: value} : t)
      } else {
        removeTodo(index)
      }
    }
  }

  const removeCompleted = () => {
    todos.value = filters.active(todos.value)
  }

  effect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(todos.value))
  })

  return (
    <section className="todoapp">
      <header className="header">
        <h1>todos</h1>
        <input
          className="new-todo"
          autoFocus
          placeholder="What needs to be done?"
          onKeyDown={addTodo}
        />
      </header>
      <section className="main" style={{ display: todos.value.length ? '' : 'none' }}>
        <input
          id="toggle-all"
          className="toggle-all"
          type="checkbox"
          checked={remaining.value === 0}
          onChange={toggleAll}
        />
        <label htmlFor="toggle-all">Mark all as complete</label>
        <ul className="todo-list">
          {
            filteredTodos.value.map((todo, index) => (
              <li
                className={`todo ${todo.completed ? 'completed' : ''} ${index === editedTodo.value ? 'editing' : ''}`}
                key={todo.id}
              >
                <div className="view">
                  <input 
                    className="toggle" 
                    type="checkbox" 
                    checked={todo.completed} 
                    onChange={e => todos.value = todos.value.map(v => v.id === todo.id ? {...v, completed: e.target.checked} : v)} 
                  />
                  <label onDblClick={() => editTodo(index)}>{todo.title}</label>
                  <button className="destroy" onClick={() => removeTodo(index)}>x</button>
                </div>
                {
                  index === editedTodo.value && 
                  <input
                    className="edit"
                    type="text"
                    v-model="todo.title"
                    class="todo-edit"
                    value={todo.title}
                    onBlur={(e) => doneEdit(e.target.value.trim(), index)}
                    onKeyUp={e => {
                      if(e.key === 'Enter'){
                        doneEdit(e.target.value.trim(), index)
                      }
                      if(e.key === 'Escape'){
                        editedTodo.value = null
                      }
                    }}
                  />
                }
              </li>
            ))
          }
        </ul>
      </section>
      <footer className="footer" style={{ display: todos.value.length ? '' : 'none' }}>
        <span className="todo-count">
          <strong>{ remaining }</strong>
          <span>{ remaining === 1 ? 'item' : 'items' } left</span>
        </span>
        <ul className="filters">
        <li>
          <a href="#/all" className={ visibility === 'all' ? 'selected' : '' }>All</a>
        </li>
        <li>
          <a href="#/active" className={ visibility === 'active' ? 'selected' : '' }>Active</a>
        </li>
        <li>
          <a href="#/completed" className={ visibility === 'completed' ? 'selected' : '' }>Completed</a>
        </li>
      </ul>
      <button className="clear-completed" onClick={removeCompleted} style={{ display: todos.value.length > remaining ? '' : 'none' }}>
        Clear completed
      </button>
      </footer>
    </section >
  )
}

// angular-todomvc/src/app/app.component.ts
import { Component } from '@angular/core';

const STORAGE_KEY = 'todos-angular'

interface Todo{
  id: number;
  title: string;
  completed: boolean;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  input = ''
  todos: Todo[] = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]')
  visibility = 'all'
  editedTodo: Todo | undefined
  beforeEditCache = ''

  constructor(){
    window.addEventListener('hashchange', () => {
      const route = window.location.hash.replace(/#\/?/, '')
      if (['all', 'active', 'completed'].includes(route)) {
        this.visibility = route
      } else {
        window.location.hash = ''
        this.visibility = 'all'
      }
    })
  }

  addTodo(){
    const todo = this.input.trim()
    if (todo) {
      this.todos.push({
        id: Date.now(),
        title: todo,
        completed: false
      })
      this.input = ''
      this.storeTodos()
    }
  }

  remaining(){
    return this.todos.filter(todo => !todo.completed).length
  }

  toggleAll(event: any){
    this.todos.forEach(todo => todo.completed = event.checked)
  }

  filteredTodos(){
    if(this.visibility === 'all'){
      return this.todos
    }else if(this.visibility === 'active'){
      return this.todos.filter(todo => !todo.completed)
    }
    return this.todos.filter(todo => todo.completed)
  }

  trackByFn(index: number, item: Todo) {
    return item.id
  }

  editTodo(todo: Todo){
    this.beforeEditCache = todo.title
    this.editedTodo = todo
  }

  removeTodo(todo: Todo){
    this.todos = this.todos.filter(t => t.id !== todo.id)
    this.storeTodos()
  }

  doneEdit(todo: Todo){
    if (this.editedTodo) {
      this.editedTodo = undefined
      todo.title = todo.title.trim()
      if (!todo.title) this.removeTodo(todo)
    }
    this.storeTodos()
  }

  cancelEdit(todo: Todo) {
    this.editedTodo = undefined
    todo.title = this.beforeEditCache
  }

  removeCompleted() {
    this.todos = this.todos.filter(todo => !todo.completed)
    this.storeTodos()
  }

  storeTodos(){
    localStorage.setItem(STORAGE_KEY, JSON.stringify(this.todos))
  }
}

<div id="app">
  <section class="todoapp">
    <header class="header">
      <h1>todos</h1>
      <input
        class="new-todo"
        autofocus
        placeholder="What needs to be done?"
        [(ngModel)]="input"
        (keyup.enter)="addTodo()"
      />
    </header>
    <section class="main" v-show="todos.length">
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        [checked]="remaining() === 0"
        (change)="toggleAll($event.target)"
      />
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        <li
          *ngFor="let todo of filteredTodos(); trackBy: trackByFn"
          class="todo"
          [class.comlpeted]="todo.completed"
          [class.editing]="todo === editedTodo"
        >
          <div class="view">
            <input class="toggle" type="checkbox" [(ngModel)]="todo.completed" />
            <label (dblclick)="editTodo(todo)">{{ todo.title }}</label>
            <button class="destroy" (click)="removeTodo(todo)">x</button>
          </div>
          <input
            *ngIf="todo === editedTodo"
            class="edit"
            type="text"
            [(ngModel)]="todo.title"
            (blur)="doneEdit(todo)"
            (keyup.enter)="doneEdit(todo)"
            (keyup.escape)="cancelEdit(todo)"
          />
        </li>
      </ul>
    </section>
    <footer class="footer" v-show="todos.length">
      <span class="todo-count">
        <strong>{{ remaining() }}</strong>
        <span>{{ remaining() === 1 ? 'item' : 'items' }} left</span>
      </span>
      <ul class="filters">
        <li>
          <a href="#/all" [class.selected]="visibility === 'all'">All</a>
        </li>
        <li>
          <a href="#/active" [class.selected]="visibility === 'active'">Active</a>
        </li>
        <li>
          <a href="#/completed" [class.selected]="visibility === 'completed'">Completed</a>
        </li>
      </ul>
      <button class="clear-completed" (click)="removeCompleted()" *ngIf="todos.length > remaining()">
        Clear completed
      </button>
    </footer>
  </section>
</div>
