// preact-todomvc/src/app.jsx
import { signal, computed, effect } from '@preact/signals'

const STORAGE_KEY = 'todos-preact'

const filters = {
  all: (todos) => todos,
  active: (todos) => todos.filter((todo) => !todo.completed),
  completed: (todos) => todos.filter((todo) => todo.completed)
}

const visibility = signal('all')

function onHashChange() {
  const route = window.location.hash.replace(/#\/?/, '')
  if (filters[route]) {
    visibility.value = route
  } else {
    window.location.hash = ''
    visibility.value = 'all'
  }
}

window.addEventListener('hashchange', onHashChange)
onHashChange()

const editedTodo = signal(null);
const todos = signal(JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'))
const filteredTodos = computed(() => filters[visibility.value](todos.value))
const remaining = computed(() => filters.active(todos.value).length)

export function App() {
  const addTodo = (event) => {
    if (event.key === 'Enter') {
      const value = event.target.value.trim()
      if (value) {
        todos.value = [...todos.value,
          {
            id: Date.now(),
            title: value,
            completed: false,
          }
        ]
        event.target.value = ''
      }
    }
  }

  const removeTodo = (index) => {
    const array = [...todos.value]
    array.splice(index, 1)
    todos.value = array
  }

  const toggleAll = (e) => {
    todos.value = todos.value.map(v => ({...v, completed: e.target.checked}))
  }

  const editTodo = (index) => {
    editedTodo.value = index
    setTimeout(() => {
      document.querySelector('.todo-edit').focus()
    }, 10);
  }
  
  const doneEdit = (value, index) => {
    if (editedTodo.value !== null) {
      editedTodo.value = null
      if(value) {
        todos.value = todos.value.map((t,i) => i === index ? {...t, title: value} : t)
      } else {
        removeTodo(index)
      }
    }
  }

  const removeCompleted = () => {
    todos.value = filters.active(todos.value)
  }

  effect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(todos.value))
  })

  return (
    <section className="todoapp">
      <header className="header">
        <h1>todos</h1>
        <input
          className="new-todo"
          autoFocus
          placeholder="What needs to be done?"
          onKeyDown={addTodo}
        />
      </header>
      <section className="main" style={{ display: todos.value.length ? '' : 'none' }}>
        <input
          id="toggle-all"
          className="toggle-all"
          type="checkbox"
          checked={remaining.value === 0}
          onChange={toggleAll}
        />
        <label htmlFor="toggle-all">Mark all as complete</label>
        <ul className="todo-list">
          {
            filteredTodos.value.map((todo, index) => (
              <li
                className={`todo ${todo.completed ? 'completed' : ''} ${index === editedTodo.value ? 'editing' : ''}`}
                key={todo.id}
              >
                <div className="view">
                  <input 
                    className="toggle" 
                    type="checkbox" 
                    checked={todo.completed} 
                    onChange={e => todos.value = todos.value.map(v => v.id === todo.id ? {...v, completed: e.target.checked} : v)} 
                  />
                  <label onDblClick={() => editTodo(index)}>{todo.title}</label>
                  <button className="destroy" onClick={() => removeTodo(index)}>x</button>
                </div>
                {
                  index === editedTodo.value && 
                  <input
                    className="edit"
                    type="text"
                    v-model="todo.title"
                    class="todo-edit"
                    value={todo.title}
                    onBlur={(e) => doneEdit(e.target.value.trim(), index)}
                    onKeyUp={e => {
                      if(e.key === 'Enter'){
                        doneEdit(e.target.value.trim(), index)
                      }
                      if(e.key === 'Escape'){
                        editedTodo.value = null
                      }
                    }}
                  />
                }
              </li>
            ))
          }
        </ul>
      </section>
      <footer className="footer" style={{ display: todos.value.length ? '' : 'none' }}>
        <span className="todo-count">
          <strong>{ remaining }</strong>
          <span>{ remaining === 1 ? 'item' : 'items' } left</span>
        </span>
        <ul className="filters">
        <li>
          <a href="#/all" className={ visibility === 'all' ? 'selected' : '' }>All</a>
        </li>
        <li>
          <a href="#/active" className={ visibility === 'active' ? 'selected' : '' }>Active</a>
        </li>
        <li>
          <a href="#/completed" className={ visibility === 'completed' ? 'selected' : '' }>Completed</a>
        </li>
      </ul>
      <button className="clear-completed" onClick={removeCompleted} style={{ display: todos.value.length > remaining ? '' : 'none' }}>
        Clear completed
      </button>
      </footer>
    </section >
  )
}

// svelte-5-todomvc/src/App.svelte
<script>
  const ENTER_KEY = 13;
	const ESCAPE_KEY = 27;

	const STORAGE_KEY = 'todos-svelte-5'

	let currentFilter = $state('all');
	let items = $state(JSON.parse(localStorage.getItem(STORAGE_KEY)) || []);
	let editing = $state(null);

	const updateView = () => {
		currentFilter = 'all';
		if (window.location.hash === '#/active') {
			currentFilter = 'active';
		} else if (window.location.hash === '#/completed') {
			currentFilter = 'completed';
		}
	};

	window.addEventListener('hashchange', updateView);
	updateView();

	function clearCompleted() {
		items = items.filter(item => !item.completed);
	}

	function remove(index) {
		items = items.slice(0, index).concat(items.slice(index + 1));
	}

	function toggleAll(event) {
		items = items.map(item => ({
			id: item.id,
			description: item.description,
			completed: event.target.checked
		}));
	}

	function createNew(event) {
		if (event.which === ENTER_KEY) {
			items = items.concat({
				id: Date.now(),
				description: event.target.value,
				completed: false
			});
			event.target.value = '';
		}
	}

	function handleEdit(event) {
		if (event.which === ENTER_KEY) event.target.blur();
		else if (event.which === ESCAPE_KEY) editing = null;
	}

	function submit(event) {
    if(editing != null) {
      const desc = event.target.value.trim()
      if(desc) {
        items[editing].description = desc;
      } else {
        remove(editing)
      }
      editing = null;
    }
	}
	
	let filtered = $derived(currentFilter === 'all'
		? items
		: currentFilter === 'completed'
			? items.filter(item => item.completed)
			: items.filter(item => !item.completed));

	let numActive = $derived(items.filter(item => !item.completed).length);
	let numCompleted = $derived(items.filter(item => item.completed).length);

  $effect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
  })
</script>

<header class="header">
	<h1>todos</h1>
	<input
		class="new-todo"
		on:keydown={createNew}
		placeholder="What needs to be done?"
		autofocus
	>
</header>

{#if items.length > 0}
	<section class="main">
		<input id="toggle-all" class="toggle-all" type="checkbox" on:change={toggleAll} checked="{numCompleted === items.length}">
		<label for="toggle-all">Mark all as complete</label>

		<ul class="todo-list">
			{#each filtered as item, index (item.id)}
				<li class="{item.completed ? 'completed' : ''} {editing === index ? 'editing' : ''}">
					<div class="view">
						<input class="toggle" type="checkbox" bind:checked={item.completed}>
						<label on:dblclick="{() => editing = index}">{item.description}</label>
						<button on:click="{() => remove(index)}" class="destroy">x</button>
					</div>

					{#if editing === index}
						<input
							value='{item.description}'
							id="edit"
							class="edit"
							on:keydown={handleEdit}
							on:blur={submit}
							autofocus
						>
					{/if}
				</li>
			{/each}
		</ul>

		<footer class="footer">
			<span class="todo-count">
				<strong>{numActive}</strong> {numActive === 1 ? 'item' : 'items'} left
			</span>

			<ul class="filters">
				<li><a class="{currentFilter === 'all' ? 'selected' : ''}" href="#/">All</a></li>
				<li><a class="{currentFilter === 'active' ? 'selected' : ''}" href="#/active">Active</a></li>
				<li><a class="{currentFilter === 'completed' ? 'selected' : ''}" href="#/completed">Completed</a></li>
			</ul>

			{#if numCompleted}
				<button class="clear-completed" on:click={clearCompleted}>
					Clear completed
				</button>
			{/if}
		</footer>
	</section>
{/if}
